linters:
  enable-all: true
  disable:
    - contextcheck # too many false positives
    - deadcode # deprecated (since v1.49.0) and replaced by 'unused'
    - depguard # checks if package imports are whitelisted
    - exhaustivestruct # deprecated (since v1.46.0) and replaced by 'exhaustruct'
    - exhaustruct # TODO enable and fix, use regex to exclude certain cases
    - golint # deprecated (since v1.41.0) and replaced by 'revive'
    - ifshort # deprecated (since v1.48.0)
    - interfacer # deprecated (since v1.38.0)
    - lll
    - maligned # deprecated (since v1.38.0)
    - nlreturn # too strict and mostly code is not more readable
    - nosnakecase  # deprecated (since v1.48.1) and replaced by 'revive'
    - scopelint # deprecated (since v1.39.0) and replaced by 'exportloopref'
    - structcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - sqlclosecheck # not needed for this project
    - varcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - wsl # too strict and mostly code is not more readable
    ### disabled for now... will be enabled 1 by 1
    - containedctx
    - dupl
    - dupword
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godox
    - goerr113
    - gofumpt
    - gofmt
    - gomnd
    - gomoddirectives
    - gosec
    - inamedparam
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - stylecheck
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - godot
    - goimports
    - mirror
    - tagalign
    - whitespace

linters-settings:
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
  revive:
    enable-all-rules: false
    severity: error
    rules:
      - name: comment-spacings
        disabled: true
      - name: dot-imports
        severity: warning
        disabled: true
      - name: line-length-limit
        severity: warning
        disabled: true
        arguments: [ 120 ]
  funlen:
    lines: 80
  cyclop:
    max-complexity: 20
  nestif:
    min-complexity: 6
  gci:
    sections:
      - standard                                             # Standard packages.
      - default                                              # Imports that could not be matched to another section type.
      - prefix(github.com/kyma-project/eventing-manager)    # Imports with the specified prefix.
      - blank                                                # Blank imports.
      - dot                                                  # Dot imports.
    custom-order: true
    skip-generated: true
  importas:
    no-unaliased: false
    no-extra-aliases: true
    ## kubernetes APIs get the prefix `k`. As an example check `kcorev1`

    alias:
      - pkg: k8s.io/api/core/v1
        alias: kcorev1
      - pkg: k8s.io/api/apps/v1
        alias: kappsv1
      - pkg: k8s.io/api/rbac/v1
        alias: krbacv1
      - pkg: k8s.io/apimachinery/pkg/runtime/schema
        alias: kschema
      - pkg: k8s.io/apimachinery/pkg/labels
        alias: klabels
      - pkg: k8s.io/apimachinery/pkg/runtime
        alias: kruntime
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
        alias: kunstructured
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: kmetav1
      - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha1
        alias: eventingv1alpha1
      - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha2
        alias: eventingv1alpha2
      - pkg: github.com/kyma-project/eventing-manager/api/operator/v1alpha1
        alias: operatorv1alpha1
      - pkg: github.com/kyma-incubator/api-gateway/api/v1beta1
        alias: apigateway
      - pkg: k8s.io/client-go/dynamic/fake
        alias: kdynamicfake
      - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake
        alias: kapiclientsetfake
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: kerrors
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: kapiextensionsv1
      - pkg: github.com/kyma-project/eventing-manager/testing
        alias: eventingtesting
      - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
        alias: kapiclientset
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      - pkg: sigs.k8s.io/controller-runtime/pkg/log
        alias: ctrllog
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - Client
      - client.Object
      - (or|er)$
  wrapcheck:
    ignorePackageGlobs:
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - wrapcheck
    - linters:
      - importas
      text: has alias "" which is not part of config # Ignore false positives that emerged due to https://github.com/julz/importas/issues/15.
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  sort-results: true
run:
  timeout: 15m
  skip-files:
    - zz_generated.deepcopy.go
