version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - copyloopvar
    - depguard
    - dupl
    - exhaustruct
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - paralleltest
    - perfsprint
    - prealloc
    - sqlclosecheck
    - testpackage
    - wrapcheck
    - wsl
    - funcorder # TODO: remove
    - gosec # TODO: remove
    - recvcheck # TODO: remove
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 80
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: kcorev1
        - pkg: k8s.io/api/apps/v1
          alias: kappsv1
        - pkg: k8s.io/api/rbac/v1
          alias: krbacv1
        - pkg: k8s.io/api/batch/v1
          alias: kbatchv1
        - pkg: k8s.io/apimachinery/pkg/runtime/schema
          alias: kschema
        - pkg: k8s.io/apimachinery/pkg/labels
          alias: klabels
        - pkg: k8s.io/apimachinery/pkg/runtime
          alias: kruntime
        - pkg: k8s.io/apimachinery/pkg/types
          alias: ktypes
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
          alias: kunstructured
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: kmetav1
        - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha2
          alias: eventingv1alpha2
        - pkg: github.com/kyma-project/eventing-manager/api/operator/v1alpha1
          alias: operatorv1alpha1
        - pkg: github.com/kyma-project/api-gateway/apis/gateway/v1beta1
          alias: apigatewayv1beta1
        - pkg: k8s.io/client-go/dynamic/fake
          alias: kdynamicfake
        - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
          alias: kapixclientset
        - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake
          alias: kapixclientsetfake
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: kerrors
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: kapiextensionsv1
        - pkg: github.com/kyma-project/eventing-manager/testing
          alias: eventingtesting
        - pkg: sigs.k8s.io/controller-runtime
          alias: kctrl
        - pkg: sigs.k8s.io/controller-runtime/pkg/reconcile
          alias: kctrlruntimereconcile
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: kctrllog
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: kctrlclient
        - pkg: k8s.io/api/autoscaling/v1
          alias: kautoscalingv1
        - pkg: k8s.io/api/autoscaling/v2
          alias: kautoscalingv2
        - pkg: k8s.io/api/admissionregistration/v1
          alias: kadmissionregistrationv1
        - pkg: github.com/cloudevents/sdk-go/v2
          alias: cloudevents
        - pkg: github.com/cloudevents/sdk-go/protocol/nats/v2
          alias: cenats
        - pkg: github.com/cloudevents/sdk-go/v2/binding
          alias: cebinding
        - pkg: github.com/cloudevents/sdk-go/v2/client
          alias: ceclient
        - pkg: github.com/cloudevents/sdk-go/v2/event
          alias: ceevent
        - pkg: github.com/cloudevents/sdk-go/v2/protocol
          alias: ceprotocol
        - pkg: github.com/cloudevents/sdk-go/v2/protocol/http
          alias: cehttp
        - pkg: github.com/kyma-project/eventing-manager/pkg/backend/(\w+)$
          alias: backend$1
        - pkg: github.com/kyma-project/eventing-manager/pkg/backend/(\w+)/(\w+)$
          alias: backend$1$2
        - pkg: github.com/kyma-project/eventing-manager/test/(\w+)$
          alias: test$1
        - pkg: github.com/kyma-project/eventing-manager/test/(\w+)/(\w+)$
          alias: test$1$2
        - pkg: istio.io/client-go/pkg/apis/security/v1beta1
          alias: istiopkgsecurityv1beta1
        - pkg: istio.io/api/(\w+)/(v\d+\w*\d*)$
          alias: istio$1$2
        - pkg: github.com/nats-io/nats-server/v2/(\w+)$
          alias: natsio$1
        - pkg: github.com/nats-io/nats.go
          alias: natsio
        - pkg: github.com/kyma-project/eventing-manager/internal/controller/(\w+)$
          alias: controller$1
        - pkg: github.com/kyma-project/kyma/common/logging/logger
          alias: kymalogger
        - pkg: github.com/kyma-project/nats-manager/api/v1alpha1
          alias: natsv1alpha1
        - pkg: github.com/kyma-project/nats-manager/testutils
          alias: natstestutils
        - pkg: github.com/kyma-project/eventing-manager/internal/connection/nats
          alias: natsconnection
        - pkg: github.com/kyma-project/eventing-manager/internal/connection/nats/errors
          alias: natsconnectionerrors
        - pkg: github.com/kyma-project/eventing-manager/internal/connection/nats/mocks
          alias: natsconnectionmocks
        - pkg: github.com/kyma-project/eventing-manager/internal/controller/eventing/subscription/(\w+)$
          alias: subscriptioncontroller$1
        - pkg: github.com/kyma-project/eventing-manager/internal/controller/operator/eventing
          alias: eventingcontroller
        - pkg: github.com/kyma-project/eventing-manager/internal/controller/operator/eventing/mocks
          alias: eventingcontrollermocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/ems/api/events/client/mocks
          alias: emsclientmocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/ems/api/events/types
          alias: emstypes
        - pkg: github.com/onsi/gomega/types
          alias: gomegatypes
        - pkg: k8s.io/apimachinery/pkg/util/runtime
          alias: kutilruntime
        - pkg: k8s.io/client-go/kubernetes/scheme
          alias: kkubernetesscheme
        - pkg: github.com/kyma-project/eventing-manager/pkg/subscriptionmanager/manager
          alias: submgrmanager
        - pkg: github.com/kyma-project/eventing-manager/pkg/subscriptionmanager/manager/mocks
          alias: submgrmanagermocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/subscriptionmanager/mocks
          alias: submgrmocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/watcher/mocks
          alias: watchermocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/k8s/mocks
          alias: k8smocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/eventing/mocks
          alias: eventingmocks
        - pkg: github.com/kyma-project/eventing-manager/pkg/errors
          alias: emerrors
        - pkg: github.com/pkg/errors
          alias: pkgerrors
        - pkg: github.com/kyma-project/eventing-manager/testing/eventmeshsub
          alias: eventmeshsubmatchers
        - pkg: github.com/kyma-project/eventing-manager/internal/controller/eventing/subscription/validator/mocks
          alias: subscriptionvalidatormocks
      no-unaliased: false
      no-extra-aliases: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - Client
        - client.Object
        - (or|er)$
    nestif:
      min-complexity: 6
    revive:
      severity: error
      enable-all-rules: false
      rules:
        - name: comment-spacings
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
    varnamelen:
      ignore-names:
        - ok
        - g
        - a
        - b
        - tc
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - i int
        - g *gomega.WithT
        - w http.ResponseWriter
        - r *http.Request
        - cm *v1.ConfigMap
        - cm *kcorev1.ConfigMap
        - js JetStream
        - js *JetStream
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - maintidx
          - wrapcheck
        path: _test\.go
      - linters:
          - importas
        text: has alias "" which is not part of config
      - linters:
          - lll
        source: '^// +kubebuilder: '
    paths:
      - zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kyma-project/eventing-manager)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
