apiVersion: v1
data:
  eventTypePrefix: sap.kyma.custom
kind: ConfigMap
metadata:
  labels:
    control-plane: eventing-manager
    app.kubernetes.io/name: eventing
    app.kubernetes.io/instance: eventing-manager
    app.kubernetes.io/component: eventing-manager
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
  name: eventing
  namespace: system
