apiVersion: v1
kind: Service
metadata:
  name: eventing-manager-metrics
  labels:
    control-plane: eventing-manager
    app.kubernetes.io/name: eventing-manager
    app.kubernetes.io/instance: eventing-manager
    app.kubernetes.io/component: eventing-manager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    control-plane: eventing-manager
    app.kubernetes.io/name: eventing-manager
    app.kubernetes.io/instance: eventing-manager
    app.kubernetes.io/component: eventing-manager
  ports:
    - name: http-metrics
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eventing-manager-health
  labels:
    control-plane: eventing-manager
    app.kubernetes.io/name: eventing-manager
    app.kubernetes.io/instance: eventing-manager
    app.kubernetes.io/component: eventing-manager
spec:
  type: ClusterIP
  selector:
    control-plane: eventing-manager
    app.kubernetes.io/name: eventing-manager
    app.kubernetes.io/instance: eventing-manager
    app.kubernetes.io/component: eventing-manager
  ports:
    - name:  http-status
      protocol: TCP
      port: 15020
      targetPort: 15020
