apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: subscription-mutating-webhook-configuration
  labels:
    app.kubernetes.io/name: subscription-mutating-webhook-configuration
    app.kubernetes.io/component: eventing-manager
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: eventing-manager-webhook-service
      namespace: kyma-system
      path: /mutate-eventing-kyma-project-io-v1alpha2-subscription
  failurePolicy: Fail
  name: msubscription.kb.io
  rules:
  - apiGroups:
    - eventing.kyma-project.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - subscriptions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: subscription-validating-webhook-configuration
  labels:
    app.kubernetes.io/name: subscription-validating-webhook-configuration
    app.kubernetes.io/component: eventing-manager
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: eventing-manager-webhook-service
      namespace: kyma-system
      path: /validate-eventing-kyma-project-io-v1alpha2-subscription
  failurePolicy: Fail
  name: vsubscription.kb.io
  rules:
  - apiGroups:
    - eventing.kyma-project.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - subscriptions
  sideEffects: None
