apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: eventing-manager-metrics
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
  name: eventing-manager-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: manager
