apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: eventing-manager
    app.kubernetes.io/instance: manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
  name: eventing-manager
  namespace: system
