apiVersion: operator.kyma-project.io/v1alpha1
kind: Eventing
metadata:
  labels:
    app.kubernetes.io/name: eventing
    app.kubernetes.io/instance: eventing
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/created-by: eventing-manager
  name: eventing
  namespace: kyma-system
spec:
  publisher:
    replicas:
      min: 2
      max: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 40m
        memory: 64Mi
