apiVersion: operator.kyma-project.io/v1alpha1
kind: Eventing
metadata:
  labels:
    app.kubernetes.io/name: eventing
    app.kubernetes.io/instance: eventing-sample
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: eventing-manager
  name: eventing
  namespace: kyma-system
spec:
  backend:
    type: NATS
    config:
      natsStreamStorageType: File
      natsStreamReplicas: 3
      natsStreamMaxSize: 700M
      natsMaxMsgsPerTopic: 1000000
  publisher:
    replicas:
      min: 2
      max: 2
    resources:
      limits:
        cpu: 300m
        memory: 312Mi
      requests:
        cpu: 100m
        memory: 156Mi
