// Code generated by mockery v2.39.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	nats_go "github.com/nats-io/nats.go"
)

// Connection is an autogenerated mock type for the Interface type
type Connection struct {
	mock.Mock
}

type Connection_Expecter struct {
	mock *mock.Mock
}

func (_m *Connection) EXPECT() *Connection_Expecter {
	return &Connection_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields:
func (_m *Connection) Connect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Connection_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *Connection_Expecter) Connect() *Connection_Connect_Call {
	return &Connection_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *Connection_Connect_Call) Run(run func()) *Connection_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Connect_Call) Return(_a0 error) *Connection_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connection_Connect_Call) RunAndReturn(run func() error) *Connection_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields:
func (_m *Connection) Disconnect() {
	_m.Called()
}

// Connection_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type Connection_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *Connection_Expecter) Disconnect() *Connection_Disconnect_Call {
	return &Connection_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *Connection_Disconnect_Call) Run(run func()) *Connection_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Disconnect_Call) Return() *Connection_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Connection_Disconnect_Call) RunAndReturn(run func()) *Connection_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDisconnectErrHandlerIfNotRegistered provides a mock function with given fields: _a0
func (_m *Connection) RegisterDisconnectErrHandlerIfNotRegistered(_a0 nats_go.ConnErrHandler) {
	_m.Called(_a0)
}

// Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDisconnectErrHandlerIfNotRegistered'
type Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call struct {
	*mock.Call
}

// RegisterDisconnectErrHandlerIfNotRegistered is a helper method to define mock.On call
//   - _a0 nats_go.ConnErrHandler
func (_e *Connection_Expecter) RegisterDisconnectErrHandlerIfNotRegistered(_a0 interface{}) *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call {
	return &Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call{Call: _e.mock.On("RegisterDisconnectErrHandlerIfNotRegistered", _a0)}
}

func (_c *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call) Run(run func(_a0 nats_go.ConnErrHandler)) *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(nats_go.ConnErrHandler))
	})
	return _c
}

func (_c *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call) Return() *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call {
	_c.Call.Return()
	return _c
}

func (_c *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call) RunAndReturn(run func(nats_go.ConnErrHandler)) *Connection_RegisterDisconnectErrHandlerIfNotRegistered_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterReconnectHandlerIfNotRegistered provides a mock function with given fields: _a0
func (_m *Connection) RegisterReconnectHandlerIfNotRegistered(_a0 nats_go.ConnHandler) {
	_m.Called(_a0)
}

// Connection_RegisterReconnectHandlerIfNotRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterReconnectHandlerIfNotRegistered'
type Connection_RegisterReconnectHandlerIfNotRegistered_Call struct {
	*mock.Call
}

// RegisterReconnectHandlerIfNotRegistered is a helper method to define mock.On call
//   - _a0 nats_go.ConnHandler
func (_e *Connection_Expecter) RegisterReconnectHandlerIfNotRegistered(_a0 interface{}) *Connection_RegisterReconnectHandlerIfNotRegistered_Call {
	return &Connection_RegisterReconnectHandlerIfNotRegistered_Call{Call: _e.mock.On("RegisterReconnectHandlerIfNotRegistered", _a0)}
}

func (_c *Connection_RegisterReconnectHandlerIfNotRegistered_Call) Run(run func(_a0 nats_go.ConnHandler)) *Connection_RegisterReconnectHandlerIfNotRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(nats_go.ConnHandler))
	})
	return _c
}

func (_c *Connection_RegisterReconnectHandlerIfNotRegistered_Call) Return() *Connection_RegisterReconnectHandlerIfNotRegistered_Call {
	_c.Call.Return()
	return _c
}

func (_c *Connection_RegisterReconnectHandlerIfNotRegistered_Call) RunAndReturn(run func(nats_go.ConnHandler)) *Connection_RegisterReconnectHandlerIfNotRegistered_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnection creates a new instance of Connection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connection {
	mock := &Connection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
