---
# Source: publisher-proxy/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: publisher-proxy-clusterrole
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: publisher-proxy-clusterrole
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize 
rules:
- apiGroups:
  - eventing.kyma-project.io
  resources:
  - subscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - applicationconnector.kyma-project.io
  resources:
    - applications
  verbs:
    - get
    - list
    - watch
