apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: publisher-proxy-hpa
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: hpa
    app.kubernetes.io/instance: publisher-proxy-hpa
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: publisher-proxy
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50