---
# Source: publisher-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: publisher-proxy
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: publisher-proxy
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
