// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	env "github.com/kyma-project/eventing-manager/pkg/env"
	mock "github.com/stretchr/testify/mock"

	subscriptionmanager "github.com/kyma-project/kyma/components/eventing-controller/pkg/subscriptionmanager"

	v1alpha1 "github.com/kyma-project/eventing-manager/api/v1alpha1"
)

// ManagerFactory is an autogenerated mock type for the ManagerFactory type
type ManagerFactory struct {
	mock.Mock
}

type ManagerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ManagerFactory) EXPECT() *ManagerFactory_Expecter {
	return &ManagerFactory_Expecter{mock: &_m.Mock}
}

// NewJetStreamManager provides a mock function with given fields: _a0, _a1
func (_m *ManagerFactory) NewJetStreamManager(_a0 v1alpha1.Eventing, _a1 env.NATSConfig) subscriptionmanager.Manager {
	ret := _m.Called(_a0, _a1)

	var r0 subscriptionmanager.Manager
	if rf, ok := ret.Get(0).(func(v1alpha1.Eventing, env.NATSConfig) subscriptionmanager.Manager); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(subscriptionmanager.Manager)
		}
	}

	return r0
}

// ManagerFactory_NewJetStreamManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewJetStreamManager'
type ManagerFactory_NewJetStreamManager_Call struct {
	*mock.Call
}

// NewJetStreamManager is a helper method to define mock.On call
//   - _a0 v1alpha1.Eventing
//   - _a1 env.NATSConfig
func (_e *ManagerFactory_Expecter) NewJetStreamManager(_a0 interface{}, _a1 interface{}) *ManagerFactory_NewJetStreamManager_Call {
	return &ManagerFactory_NewJetStreamManager_Call{Call: _e.mock.On("NewJetStreamManager", _a0, _a1)}
}

func (_c *ManagerFactory_NewJetStreamManager_Call) Run(run func(_a0 v1alpha1.Eventing, _a1 env.NATSConfig)) *ManagerFactory_NewJetStreamManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(v1alpha1.Eventing), args[1].(env.NATSConfig))
	})
	return _c
}

func (_c *ManagerFactory_NewJetStreamManager_Call) Return(_a0 subscriptionmanager.Manager) *ManagerFactory_NewJetStreamManager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ManagerFactory_NewJetStreamManager_Call) RunAndReturn(run func(v1alpha1.Eventing, env.NATSConfig) subscriptionmanager.Manager) *ManagerFactory_NewJetStreamManager_Call {
	_c.Call.Return(run)
	return _c
}

// NewManagerFactory creates a new instance of ManagerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagerFactory {
	mock := &ManagerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
