// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "k8s.io/apimachinery/pkg/runtime"

	v1 "k8s.io/api/apps/v1"

	v1alpha1 "github.com/kyma-project/eventing-manager/api/v1alpha1"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateHPA provides a mock function with given fields: ctx, deployment, _a2, cpuUtilization, memoryUtilization
func (_m *Manager) CreateOrUpdateHPA(ctx context.Context, deployment *v1.Deployment, _a2 *v1alpha1.Eventing, cpuUtilization int32, memoryUtilization int32) error {
	ret := _m.Called(ctx, deployment, _a2, cpuUtilization, memoryUtilization)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Deployment, *v1alpha1.Eventing, int32, int32) error); ok {
		r0 = rf(ctx, deployment, _a2, cpuUtilization, memoryUtilization)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_CreateOrUpdateHPA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateHPA'
type Manager_CreateOrUpdateHPA_Call struct {
	*mock.Call
}

// CreateOrUpdateHPA is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *v1.Deployment
//   - _a2 *v1alpha1.Eventing
//   - cpuUtilization int32
//   - memoryUtilization int32
func (_e *Manager_Expecter) CreateOrUpdateHPA(ctx interface{}, deployment interface{}, _a2 interface{}, cpuUtilization interface{}, memoryUtilization interface{}) *Manager_CreateOrUpdateHPA_Call {
	return &Manager_CreateOrUpdateHPA_Call{Call: _e.mock.On("CreateOrUpdateHPA", ctx, deployment, _a2, cpuUtilization, memoryUtilization)}
}

func (_c *Manager_CreateOrUpdateHPA_Call) Run(run func(ctx context.Context, deployment *v1.Deployment, _a2 *v1alpha1.Eventing, cpuUtilization int32, memoryUtilization int32)) *Manager_CreateOrUpdateHPA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Deployment), args[2].(*v1alpha1.Eventing), args[3].(int32), args[4].(int32))
	})
	return _c
}

func (_c *Manager_CreateOrUpdateHPA_Call) Return(_a0 error) *Manager_CreateOrUpdateHPA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_CreateOrUpdateHPA_Call) RunAndReturn(run func(context.Context, *v1.Deployment, *v1alpha1.Eventing, int32, int32) error) *Manager_CreateOrUpdateHPA_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdatePublisherProxy provides a mock function with given fields: ctx, _a1, backendType
func (_m *Manager) CreateOrUpdatePublisherProxy(ctx context.Context, _a1 *v1alpha1.Eventing, backendType v1alpha1.BackendType) (*v1.Deployment, error) {
	ret := _m.Called(ctx, _a1, backendType)

	var r0 *v1.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing, v1alpha1.BackendType) (*v1.Deployment, error)); ok {
		return rf(ctx, _a1, backendType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing, v1alpha1.BackendType) *v1.Deployment); ok {
		r0 = rf(ctx, _a1, backendType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Eventing, v1alpha1.BackendType) error); ok {
		r1 = rf(ctx, _a1, backendType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_CreateOrUpdatePublisherProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdatePublisherProxy'
type Manager_CreateOrUpdatePublisherProxy_Call struct {
	*mock.Call
}

// CreateOrUpdatePublisherProxy is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1alpha1.Eventing
//   - backendType v1alpha1.BackendType
func (_e *Manager_Expecter) CreateOrUpdatePublisherProxy(ctx interface{}, _a1 interface{}, backendType interface{}) *Manager_CreateOrUpdatePublisherProxy_Call {
	return &Manager_CreateOrUpdatePublisherProxy_Call{Call: _e.mock.On("CreateOrUpdatePublisherProxy", ctx, _a1, backendType)}
}

func (_c *Manager_CreateOrUpdatePublisherProxy_Call) Run(run func(ctx context.Context, _a1 *v1alpha1.Eventing, backendType v1alpha1.BackendType)) *Manager_CreateOrUpdatePublisherProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Eventing), args[2].(v1alpha1.BackendType))
	})
	return _c
}

func (_c *Manager_CreateOrUpdatePublisherProxy_Call) Return(_a0 *v1.Deployment, _a1 error) *Manager_CreateOrUpdatePublisherProxy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_CreateOrUpdatePublisherProxy_Call) RunAndReturn(run func(context.Context, *v1alpha1.Eventing, v1alpha1.BackendType) (*v1.Deployment, error)) *Manager_CreateOrUpdatePublisherProxy_Call {
	_c.Call.Return(run)
	return _c
}

// DeployPublisherProxyResources provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Manager) DeployPublisherProxyResources(_a0 context.Context, _a1 *v1alpha1.Eventing, _a2 *v1.Deployment, _a3 *runtime.Scheme) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing, *v1.Deployment, *runtime.Scheme) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_DeployPublisherProxyResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployPublisherProxyResources'
type Manager_DeployPublisherProxyResources_Call struct {
	*mock.Call
}

// DeployPublisherProxyResources is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *v1alpha1.Eventing
//   - _a2 *v1.Deployment
//   - _a3 *runtime.Scheme
func (_e *Manager_Expecter) DeployPublisherProxyResources(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *Manager_DeployPublisherProxyResources_Call {
	return &Manager_DeployPublisherProxyResources_Call{Call: _e.mock.On("DeployPublisherProxyResources", _a0, _a1, _a2, _a3)}
}

func (_c *Manager_DeployPublisherProxyResources_Call) Run(run func(_a0 context.Context, _a1 *v1alpha1.Eventing, _a2 *v1.Deployment, _a3 *runtime.Scheme)) *Manager_DeployPublisherProxyResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Eventing), args[2].(*v1.Deployment), args[3].(*runtime.Scheme))
	})
	return _c
}

func (_c *Manager_DeployPublisherProxyResources_Call) Return(_a0 error) *Manager_DeployPublisherProxyResources_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_DeployPublisherProxyResources_Call) RunAndReturn(run func(context.Context, *v1alpha1.Eventing, *v1.Deployment, *runtime.Scheme) error) *Manager_DeployPublisherProxyResources_Call {
	_c.Call.Return(run)
	return _c
}

// IsNATSAvailable provides a mock function with given fields: ctx, namespace
func (_m *Manager) IsNATSAvailable(ctx context.Context, namespace string) (bool, error) {
	ret := _m.Called(ctx, namespace)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_IsNATSAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNATSAvailable'
type Manager_IsNATSAvailable_Call struct {
	*mock.Call
}

// IsNATSAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *Manager_Expecter) IsNATSAvailable(ctx interface{}, namespace interface{}) *Manager_IsNATSAvailable_Call {
	return &Manager_IsNATSAvailable_Call{Call: _e.mock.On("IsNATSAvailable", ctx, namespace)}
}

func (_c *Manager_IsNATSAvailable_Call) Run(run func(ctx context.Context, namespace string)) *Manager_IsNATSAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Manager_IsNATSAvailable_Call) Return(_a0 bool, _a1 error) *Manager_IsNATSAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_IsNATSAvailable_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Manager_IsNATSAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
