// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	env "github.com/kyma-project/eventing-manager/pkg/env"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/apps/v1"

	v1alpha1 "github.com/kyma-project/eventing-manager/api/operator/v1alpha1"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// DeletePublisherProxyResources provides a mock function with given fields: ctx, _a1
func (_m *Manager) DeletePublisherProxyResources(ctx context.Context, _a1 *v1alpha1.Eventing) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeletePublisherProxyResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_DeletePublisherProxyResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePublisherProxyResources'
type Manager_DeletePublisherProxyResources_Call struct {
	*mock.Call
}

// DeletePublisherProxyResources is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1alpha1.Eventing
func (_e *Manager_Expecter) DeletePublisherProxyResources(ctx interface{}, _a1 interface{}) *Manager_DeletePublisherProxyResources_Call {
	return &Manager_DeletePublisherProxyResources_Call{Call: _e.mock.On("DeletePublisherProxyResources", ctx, _a1)}
}

func (_c *Manager_DeletePublisherProxyResources_Call) Run(run func(ctx context.Context, _a1 *v1alpha1.Eventing)) *Manager_DeletePublisherProxyResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Eventing))
	})
	return _c
}

func (_c *Manager_DeletePublisherProxyResources_Call) Return(_a0 error) *Manager_DeletePublisherProxyResources_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_DeletePublisherProxyResources_Call) RunAndReturn(run func(context.Context, *v1alpha1.Eventing) error) *Manager_DeletePublisherProxyResources_Call {
	_c.Call.Return(run)
	return _c
}

// DeployPublisherProxy provides a mock function with given fields: ctx, _a1, natsConfig, backendType
func (_m *Manager) DeployPublisherProxy(ctx context.Context, _a1 *v1alpha1.Eventing, natsConfig *env.NATSConfig, backendType v1alpha1.BackendType) (*v1.Deployment, error) {
	ret := _m.Called(ctx, _a1, natsConfig, backendType)

	if len(ret) == 0 {
		panic("no return value specified for DeployPublisherProxy")
	}

	var r0 *v1.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing, *env.NATSConfig, v1alpha1.BackendType) (*v1.Deployment, error)); ok {
		return rf(ctx, _a1, natsConfig, backendType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing, *env.NATSConfig, v1alpha1.BackendType) *v1.Deployment); ok {
		r0 = rf(ctx, _a1, natsConfig, backendType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Eventing, *env.NATSConfig, v1alpha1.BackendType) error); ok {
		r1 = rf(ctx, _a1, natsConfig, backendType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_DeployPublisherProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployPublisherProxy'
type Manager_DeployPublisherProxy_Call struct {
	*mock.Call
}

// DeployPublisherProxy is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1alpha1.Eventing
//   - natsConfig *env.NATSConfig
//   - backendType v1alpha1.BackendType
func (_e *Manager_Expecter) DeployPublisherProxy(ctx interface{}, _a1 interface{}, natsConfig interface{}, backendType interface{}) *Manager_DeployPublisherProxy_Call {
	return &Manager_DeployPublisherProxy_Call{Call: _e.mock.On("DeployPublisherProxy", ctx, _a1, natsConfig, backendType)}
}

func (_c *Manager_DeployPublisherProxy_Call) Run(run func(ctx context.Context, _a1 *v1alpha1.Eventing, natsConfig *env.NATSConfig, backendType v1alpha1.BackendType)) *Manager_DeployPublisherProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Eventing), args[2].(*env.NATSConfig), args[3].(v1alpha1.BackendType))
	})
	return _c
}

func (_c *Manager_DeployPublisherProxy_Call) Return(_a0 *v1.Deployment, _a1 error) *Manager_DeployPublisherProxy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_DeployPublisherProxy_Call) RunAndReturn(run func(context.Context, *v1alpha1.Eventing, *env.NATSConfig, v1alpha1.BackendType) (*v1.Deployment, error)) *Manager_DeployPublisherProxy_Call {
	_c.Call.Return(run)
	return _c
}

// DeployPublisherProxyResources provides a mock function with given fields: ctx, _a1, deploy
func (_m *Manager) DeployPublisherProxyResources(ctx context.Context, _a1 *v1alpha1.Eventing, deploy *v1.Deployment) error {
	ret := _m.Called(ctx, _a1, deploy)

	if len(ret) == 0 {
		panic("no return value specified for DeployPublisherProxyResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Eventing, *v1.Deployment) error); ok {
		r0 = rf(ctx, _a1, deploy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_DeployPublisherProxyResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployPublisherProxyResources'
type Manager_DeployPublisherProxyResources_Call struct {
	*mock.Call
}

// DeployPublisherProxyResources is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1alpha1.Eventing
//   - deploy *v1.Deployment
func (_e *Manager_Expecter) DeployPublisherProxyResources(ctx interface{}, _a1 interface{}, deploy interface{}) *Manager_DeployPublisherProxyResources_Call {
	return &Manager_DeployPublisherProxyResources_Call{Call: _e.mock.On("DeployPublisherProxyResources", ctx, _a1, deploy)}
}

func (_c *Manager_DeployPublisherProxyResources_Call) Run(run func(ctx context.Context, _a1 *v1alpha1.Eventing, deploy *v1.Deployment)) *Manager_DeployPublisherProxyResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Eventing), args[2].(*v1.Deployment))
	})
	return _c
}

func (_c *Manager_DeployPublisherProxyResources_Call) Return(_a0 error) *Manager_DeployPublisherProxyResources_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_DeployPublisherProxyResources_Call) RunAndReturn(run func(context.Context, *v1alpha1.Eventing, *v1.Deployment) error) *Manager_DeployPublisherProxyResources_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackendConfig provides a mock function with no fields
func (_m *Manager) GetBackendConfig() *env.BackendConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBackendConfig")
	}

	var r0 *env.BackendConfig
	if rf, ok := ret.Get(0).(func() *env.BackendConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*env.BackendConfig)
		}
	}

	return r0
}

// Manager_GetBackendConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackendConfig'
type Manager_GetBackendConfig_Call struct {
	*mock.Call
}

// GetBackendConfig is a helper method to define mock.On call
func (_e *Manager_Expecter) GetBackendConfig() *Manager_GetBackendConfig_Call {
	return &Manager_GetBackendConfig_Call{Call: _e.mock.On("GetBackendConfig")}
}

func (_c *Manager_GetBackendConfig_Call) Run(run func()) *Manager_GetBackendConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Manager_GetBackendConfig_Call) Return(_a0 *env.BackendConfig) *Manager_GetBackendConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_GetBackendConfig_Call) RunAndReturn(run func() *env.BackendConfig) *Manager_GetBackendConfig_Call {
	_c.Call.Return(run)
	return _c
}

// IsNATSAvailable provides a mock function with given fields: ctx, namespace
func (_m *Manager) IsNATSAvailable(ctx context.Context, namespace string) (bool, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for IsNATSAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_IsNATSAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNATSAvailable'
type Manager_IsNATSAvailable_Call struct {
	*mock.Call
}

// IsNATSAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *Manager_Expecter) IsNATSAvailable(ctx interface{}, namespace interface{}) *Manager_IsNATSAvailable_Call {
	return &Manager_IsNATSAvailable_Call{Call: _e.mock.On("IsNATSAvailable", ctx, namespace)}
}

func (_c *Manager_IsNATSAvailable_Call) Run(run func(ctx context.Context, namespace string)) *Manager_IsNATSAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Manager_IsNATSAvailable_Call) Return(_a0 bool, _a1 error) *Manager_IsNATSAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_IsNATSAvailable_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Manager_IsNATSAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// SetBackendConfig provides a mock function with given fields: config
func (_m *Manager) SetBackendConfig(config env.BackendConfig) {
	_m.Called(config)
}

// Manager_SetBackendConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBackendConfig'
type Manager_SetBackendConfig_Call struct {
	*mock.Call
}

// SetBackendConfig is a helper method to define mock.On call
//   - config env.BackendConfig
func (_e *Manager_Expecter) SetBackendConfig(config interface{}) *Manager_SetBackendConfig_Call {
	return &Manager_SetBackendConfig_Call{Call: _e.mock.On("SetBackendConfig", config)}
}

func (_c *Manager_SetBackendConfig_Call) Run(run func(config env.BackendConfig)) *Manager_SetBackendConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(env.BackendConfig))
	})
	return _c
}

func (_c *Manager_SetBackendConfig_Call) Return() *Manager_SetBackendConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *Manager_SetBackendConfig_Call) RunAndReturn(run func(env.BackendConfig)) *Manager_SetBackendConfig_Call {
	_c.Run(run)
	return _c
}

// SubscriptionExists provides a mock function with given fields: ctx
func (_m *Manager) SubscriptionExists(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscriptionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_SubscriptionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscriptionExists'
type Manager_SubscriptionExists_Call struct {
	*mock.Call
}

// SubscriptionExists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Manager_Expecter) SubscriptionExists(ctx interface{}) *Manager_SubscriptionExists_Call {
	return &Manager_SubscriptionExists_Call{Call: _e.mock.On("SubscriptionExists", ctx)}
}

func (_c *Manager_SubscriptionExists_Call) Run(run func(ctx context.Context)) *Manager_SubscriptionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Manager_SubscriptionExists_Call) Return(_a0 bool, _a1 error) *Manager_SubscriptionExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_SubscriptionExists_Call) RunAndReturn(run func(context.Context) (bool, error)) *Manager_SubscriptionExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
