name: "Create release"

permissions: write-all
on:
  workflow_dispatch:
jobs:
  generate-version:
    name: Verify release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gen-version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate version number
        id: gen-version
        run: |
          VERSION="$(./hack/ci/get-version-from-branch.sh)"
          # push version to output environment file
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

  create-draft:
    name: Create draft release
    needs: [generate-version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ needs.generate-version.outputs.VERSION }}
    outputs:
      release_id: ${{ steps.create-draft.outputs.release_id }}

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.EPP_RELEASE_APP_ID }}
          private-key: ${{ secrets.EPP_RELEASE_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ steps.app-token.outputs.token }} # creating git tag using app token because GITHUB_TOKEN would not trigger build workflow (https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

      - name: Create changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./hack/ci/create_changelog.sh $VERSION

      - name: Create draft release
        id: create-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=$(./hack/ci/create_draft_release.sh $VERSION)
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Add lightweight tag to trigger release build job
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }} # creating git tag using app token because GITHUB_TOKEN would not trigger build workflow (https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).
        run: |
          # The build job will be triggered by pushing a new tag (format: x.y.z) to the repo.
          git tag $VERSION
          git push origin $VERSION

      - name: Create and upload eventing-manager.yaml and eventing-default-cr.yaml
        env:
          PULL_BASE_REF: ${{ needs.generate-version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMG: "europe-docker.pkg.dev/kyma-project/prod/eventing-manager:${VERSION}"
          MODULE_REGISTRY: "europe-docker.pkg.dev/kyma-project/prod/unsigned"
          KUSTOMIZE_VERSION: "v4.5.6"
        run: |
          ./hack/ci/render_and_upload_manifests.sh

  wait-until-build-succeeds:
    needs: [generate-version, create-draft]
    uses: "kyma-project/eventing-tools/.github/workflows/wait-build-reusable.yml@main"
    with:
      repository: ${{ github.repository_owner }}/eventing-manager
      git_ref: ${{ needs.generate-version.outputs.VERSION }}
      git_check_run_name: "build-${{ needs.generate-version.outputs.VERSION }} / Build image"

  notify-sbom:
    needs: [generate-version, wait-until-build-succeeds]
    permissions:
      id-token: write
      contents: read
    uses: "kyma-project/compliancy/.github/workflows/notify-component-sbom.yml@main"
    secrets: inherit
    with:
      component: kyma-project.io/module/eventing
      version: ${{ needs.generate-version.outputs.VERSION }}

