name: unit-test with permissions

env:
  KYMA_STABILITY: "unstable"
  KYMA: "./hack/kyma"

on:
  push:
    branches:
      - main
      - "release-**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT
  pull_request:
    branches:
      - main
      - "release-**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT
jobs:
  unit-test:
    permissions:
      content: read
    uses: kyma-project/eventing-tools/.github/workflows/unit-test-reusable-with-permission.yml@main
